// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using Newtonsoft.Json;

namespace Entropy.Responses
{
    public class VerifyUsernameResponse
    {
        [JsonProperty("valid")]
        public bool Valid { get; set; }

        [JsonProperty("suggestions")]
        public string[] Suggestions { get; set; }

        [JsonProperty("inuse")]
        public bool InUse { get; set; }
    }
}
