// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace Entropy
{

    public partial class Configuration
    {
        public class Usernames2
        {

            [JsonProperty("Prefix")]
            public string[] Prefix { get; set; }

            [JsonProperty("Root")]
            public string[] Root { get; set; }

            [JsonProperty("Suffix")]
            public string[] Suffix { get; set; }
        }
    }

    public partial class Configuration
    {
        public class Password2
        {

            [JsonProperty("UseStaticPassword")]
            public bool UseStaticPassword { get; set; }

            [JsonProperty("StaticPassword")]
            public string StaticPassword { get; set; }
        }
    }
    
    public partial class Configuration
    {
        public class Tutorial2
        {
            [JsonProperty("Tos")]
            public bool Tos { get; set; }
            
            [JsonProperty("Level2")]
            public bool Level2 { get; set; }
            
            [JsonProperty("Level5")]
            public bool Level5 { get; set; }
            
            [JsonProperty("Latitude")]
            public double Latitude { get; set; }
            
            [JsonProperty("Longitude")]
            public double Longitude { get; set; }
            
            [JsonProperty("HashKey")]
            public string HashKey { get; set; }
        }
    }

    public partial class Configuration
    {

        [JsonProperty("Usernames")]
        public Usernames2 Usernames { get; set; }

        [JsonProperty("Password")]
        public Password2 Password { get; set; }

        [JsonProperty("CaptchaKey")]
        public string CaptchaKey { get; set; }
        
        [JsonProperty("ProxyFile")]
        public string ProxyFile { get; set; }
        
        [JsonProperty("TutorialSettings")]
        public Tutorial2 TutorialSettings { get; set; }
    }

}
